### ISSUE TITLE
[studio] Slow UI regression introduced in v0.1.54

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#3456] opened 2024-04-26 10:44 UTC
### Steps to reproduce

https://github.com/mui/mui-toolpad/assets/3165635/32d94f73-6d05-4ddb-8666-858e4c30822e

### Current behavior

Super slow

### Expected behavior

As in 0.1.53

### Context

I have noticed this trying to debug https://github.com/mui/mui-toolpad/issues/3455.

Now, It feels like a low priority unless the root cause is in MUI X. I would give more priority to Toolpad Core.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: -

**Comment by Janpot** [comment] 2024-04-26 11:34
> Now, It feels like a low priority unless the root cause is in MUI X. I would give more priority to Toolpad Core.

Root cause will be in Toolpad, I think I know what happened, will take a look

**Closed** 2024-04-26 15:27 UTC
Labels: performance, regression, status: waiting for maintainer, priority: low
