### ISSUE TITLE
Better handling of deleting a page 

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1872] opened 2023-04-11 11:28 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When I delete a page, I am shown this screen:
<img width="1430" alt="Screenshot 2023-04-11 at 4 56 45 PM" src="https://user-images.githubusercontent.com/92228082/231147859-58aaf720-8187-4b66-856a-83cf281a0dd3.png">

Instead of this message, we should take the user directly to the first/default page.

Note: If the last page is deleted then the above screen doesn't come, but if any page from the middle is deleted then this screen shows.

**Comment by Janpot** [comment] 2023-04-13 09:39
I believe we should at least make sure:
* to open the first page of an application in the browser correctly on startup. Currently it opens any tab containing the `localhost:3000` domain regardless of whether the path is at a page that exists in the current application. Should we even open a new tab and not reuse it when it seems to be from a different toolpad application?
* to move to another page when a page is deleted through the UI (seems to work for me)
* to have a gracious handling of deleting the last page from the UI (not great currently, it navigates to /pages/undefined)

We should show an error message (explaining that the page does not exist) when
* The user directly opens a url to a non-existing page. The user purposefully opened this url so we should tell them it doesn't exist instead of quietly opening something they didn't intend.
* The user deletes a page on the file system that is also still open in UI

**Comment by JerryWu1234** [comment] 2023-06-07 06:54
We can prevent the user from deleting the last page

**Comment by JerryWu1234** [comment] 2023-06-07 07:30
quick question .
![image](https://github.com/mui/mui-toolpad/assets/27261522/070ed987-9bdf-41fa-a33b-18708c797892)
How do you locate which React component it is?
it doesn't have really name.

**Comment by JerryWu1234** [comment] 2023-06-07 11:00
quick question.
![image](https://github.com/mui/mui-toolpad/assets/27261522/fbe96b03-e0af-4a5d-ba0a-880be003077c)
How do you debugger code ?
every code was compressed.

**Comment by JerryWu1234** [comment] 2023-06-07 11:01
@

**Comment by Janpot** [comment] 2023-06-07 14:35
I believe there's a sourcemap problem within our runtime. Likely related to vite's virtual modules https://github.com/mui/mui-toolpad/blob/5b751066f7382c77661464b92b9b923de76c082a/packages/toolpad-app/src/server/toolpadAppBuilder.ts#L94

**Comment by JerryWu1234** [comment] 2023-06-07 14:46
Do you meet this situation?
I'm interested in how you debug

**Comment by JerryWu1234** [comment] 2023-06-26 07:16
> * to have a gracious handling of deleting the last page from the UI (not great currently, it navigates to /pages/undefined)

can I stop the user to delete the last page?

**Comment by Janpot** [comment] 2023-06-26 08:13
There should be logic for that. Could it have regressed? 

https://github.com/mui/mui-toolpad/blob/29e8d6fb1558c381da0ceed742d9420ca704e873/packages/toolpad-app/src/toolpad/AppEditor/index.tsx#L56

It's a sign that we will need a test for this logic as well

**Comment by JerryWu1234** [comment] 2023-06-26 08:57
> There should be logic for that. Could it have regressed?

if we retain the last page we can probably ignore this logic.
so that I think my idea maybe isn't a good idea.
do you have any ideas can share?

**Comment by Janpot** [comment] 2023-06-26 09:35
We should allow deleting the last page, and show this `NoPageFound` component when that happens. It has worked that way at some point. Not sure where this has regressed. Since it's a regression, we'll add a test.

We can fix this issue in a separate PR

**Comment by JerryWu1234** [comment] 2023-06-26 10:20
> We should allow deleting the last page, and show this `NoPageFound` component when that happens. It has worked that way at some point. Not sure where this has regressed. Since it's a regression, we'll add a test.
> 
> We can fix this issue in a separate PR

Ok I got it.
I done this `to move to another page when a page is deleted through the UI (seems to work for me)`

>to avoid reusing a tab when opening the browser on startup if it's not set to a page that exists in the application. Currently it tries to reuse any tab that is on the domain localhost:3000, but we should consider the pathname as well when finding a suitable tab

sorry I do not totally understand how to fix it.
![image](https://github.com/mui/mui-toolpad/assets/27261522/ab009974-6e07-465e-bde3-9aa71c84d5c0)
It seems that it feels  reasonably if a user accesses a page that doesn’t exist.

**Comment by Janpot** [comment] 2023-06-30 11:50
> sorry I do not totally understand how to fix it.

I don't believe this specific issue should be fixed in the routing layer of the toolpad editor. Instead we should fix this in the logic that tries to open the browser on startup. (https://github.com/mui/mui-toolpad/blob/7c4fa81a1b9b265815dd725a1890b393b464c8b0/packages/toolpad-app/cli/index.ts#L97). If it tries to reuse an existing tab we need to reset it to `http://localhost:PORT/` and then let the existing redirect resolve to the correct page

**Closed** 2023-06-30 17:06 UTC
Labels: bug 🐛, priority: low
