### ISSUE TITLE
Page params don't work in Edit mode

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1873] opened 2023-04-11 11:34 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Page params only work in the Preview mode and not in the Edit mode.
I am not sure if it's a fair ask, also doesn't make a big difference as Preview is just a click away but I think users might try adding params to the URL in edit mode and then doubt if something is wrong.

**Comment by Janpot** [comment] 2023-04-12 07:02
Duplicate of https://github.com/mui/mui-toolpad/issues/1624

**Closed by Janpot** 2023-04-12 07:02 UTC
Labels: duplicate
