### ISSUE TITLE
Support computed columns for the DataGrid

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#1776] opened 2023-03-21 15:35 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Would like to be able to add a column to a datagrid whose value is computed from the actual row value. Currently to achieve this, one would either have to:
- `.map` the `rows` of the datagrid in the binding editor of the `rows` prop
- `.map` the rows of the result of a code-based query before it is returned

However this is a common use case which is being worked around using code. We should provide a low-code way of achieving the same. Here we propose a way to define computed columns. Where in the column definition you can supply an expression that is evaluated in the context of the row. Under the hood it should use [`valueGetter`](https://mui.com/x/react-data-grid/column-definition/#value-getter)

## Benchmark:

* retool
![Screenshot 2023-03-21 at 16 34 19](https://user-images.githubusercontent.com/2109932/226658187-4c49d67e-5008-46a1-9697-997d66c1e949.png)

**Comment by prakhargupta1** [comment] 2023-03-28 11:03
Duplicate of: https://github.com/mui/mui-toolpad/issues/137

**Closed by prakhargupta1** 2023-03-28 11:03 UTC
Labels: new feature
