### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1720] opened 2023-03-01 11:20 UTC
We need to add a banner to inform users about the new direction of Toolpad.
Then later on, we need to update the readme.md to capture the new installation instructions.

**Comment by Janpot** [comment] 2023-03-13 15:23
Duplicate of https://github.com/mui/mui-toolpad/issues/1719

**Closed by Janpot** 2023-03-13 15:23 UTC
Labels: docs, duplicate
