### ISSUE TITLE
Support login use cases

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#2831] opened 2023-10-24 18:47 UTC
### Summary 💡

It's impossible to build real internal tools without the notion of user.

Ideally, it would support SSO with Google Workspace and Microsoft, etc. 

Once the notion of user is introduced, then come the notion of permissions https://github.com/mui/mui-toolpad/issues/352.

### Examples 🌈

- https://docs.retool.com/sso/quickstarts/google/google-sign-in
- https://refine.dev/docs/tutorial/understanding-authprovider/headless/auth-pages/#login-page
- https://marmelab.com/react-admin/Authentication.html#customizing-the-login-component

### Motivation 🔦

- https://groups.google.com/u/1/a/mui.com/g/toolpad/c/RE0ETYdyF3o

**Comment by JerryWu1234** [comment] 2023-10-25 06:20
awsome.
I invoked Google Login Api before.
i'd like to work on this if there is more details

**Comment by prakhargupta1** [comment] 2023-10-25 07:30
Duplicate of: https://github.com/mui/mui-toolpad/issues/2541

**Closed by prakhargupta1** 2023-10-25 07:30 UTC
Labels: new feature, waiting for 👍
