### ISSUE TITLE
Allow users to explore online demo from the landing page

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1041] opened 2022-09-20 18:10 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡
1. A 'Try now' type of CTA would be needed for users to quickly explore Toolpad. 
Ideally we should let users see the demo video and then show an option to try Toolpad, but then it will be too hidden. 

2. Add Google Analytics to this button.

### Example
https://usefathom.com/

**Comment by prakhargupta1** [comment] 2022-09-28 09:46
@apedroferreira Are you expecting design for this or do you have something in mind?
CC @gerdadesign

**Comment by apedroferreira** [comment] 2022-09-28 14:22
@prakhargupta1 This is separate from what I've been doing, I've just been preparing the demo in the Toolpad app itself, not the landing page (yet). So anyone could take this issue.

A design would be helpful for sure, but if it's not possible we can always try to figure something out.

**Comment by gerdadesign** [comment] 2022-10-11 19:18
Here are a couple screenshots of light & dark landing page options with the "Try demo" button. As discussed, this is almost in the same hierarchy of importance as the email sign up. 

- CTA text "Try demo" in the secondary button style matching the [pricing page](https://mui.com/pricing/). 
- added additional spacing between the chunks of information. (looks like we are using 30px bottom margin between paragraph text and button group. 
- We can stick with "Sign up" for the email CTA or we can try testing different copy (such as "Get access"). This is because we say "Sign up" in the text right above it. I've noticed some different wording throughout other early release sites and [here](https://code.luasoftware.com/tutorials/web-development/pre-launch-cta-example/) is a compilation of a few different options. 
- This also has an updated video sizing + fallback screenshot 
- And reflects the changes we discussed about bringing the promo banner closer to the features. Moving this also updates the alternating background colors on the page. 

<img width="1024" alt="Screen Shot 2022-10-11 at 3 06 38 PM" src="https://user-images.githubusercontent.com/106991024/195178178-6f0d46c7-defb-492d-89e2-d05c0588e3f3.png">


[Figma link](https://www.figma.com/file/4uv2dT18rXJPZBbrbpw61q/Marketing-site?node-id=5817%3A54280)

**Comment by gerdadesign** [comment] 2022-10-13 20:08
Ideally, we would have [both buttons on the same line](https://m3.material.io/components/all-buttons#8bb3640d-5792-4db2-befe-57139b62ac91), like this: 
<img width="672" alt="Screen Shot 2022-10-13 at 3 54 33 PM" src="https://user-images.githubusercontent.com/106991024/195696597-e42ac01e-1018-4289-9431-1bea7cee8eb8.png">

But with the email subscription text field being separate, it kind of looks muddy. 

I think putting it on top of the video would be even less discoverable as well as break expected behaviour of a play/pause button appearing on hover of the video. 

What if we could make the Sign Up CTA dynamic (and shorter confirmation copy)? Kind of like this: 
![EmailSubscribe](https://user-images.githubusercontent.com/106991024/195698438-2d488098-fd2d-4bdb-93d0-83e6c03da555.gif)

**Comment by prakhargupta1** [comment] 2022-10-14 04:43
2nd one looks great. Let's do this.

Just giving a heads-up, In the next iteration when we'll update the video with new UI, we'll also bring up the self-host button.
https://github.com/mui/mui-toolpad/issues/1132

**Comment by bharatkashyap** [comment] 2022-10-14 12:34
To me, these two CTAs are sequential - almost everyone would first want to Try the demo, and only then choose to Sign Up or not. How do we represent this hierarchy in the landing page?

One idea is to only show the "Try Demo" CTA in the first instance, and replace it with the Sign Up CTA once it has been clicked - since the user will be redirected to a separate tab and then only choose to Sign Up when they return to the landing page.

**Comment by prakhargupta1** [comment] 2022-10-18 04:11
Permanently showing a button on the video will make the video appear like a GIF that we don't want the user to focus on.

I feel we should give 'Try Demo' more importance than 'sign-up' because:
1. If only, users experience and like the demo they would think about signing up.
2. A user who won't like the demo won't sign up anyway.
3. There would be hardly any user who'll give their email ID before checking out the demo. Also, near Try demo we should mention 'No account creation required.' 

My suggestion: 
1. Show 'Try demo' as primary button
2. Show 'Sign up' as secondary button adjacent to 1. On hover, it should show email input field (similar behavior on mobile)
3. Copy can be trimmed to: 'Sign up for beta release'


For later, when we'll alter the header bar. 2 buttons in the header bar is a common practice. So in place of the search bar we can show 'Try demo' button and also bring up 'Self host' button as:
1. Search is irrelevant for Toolpad
2. A primary, secondary button pair would look good.

**Comment by gerdadesign** [comment] 2022-10-26 21:52
How about this? keeping the email button open and with extra space around Demo to separate the ideas from one another. 

![Screen Shot 2022-10-26 at 5 50 00 PM](https://user-images.githubusercontent.com/106991024/198145146-cddc8dd2-891c-4040-a609-e4d93606ce8c.png)

I did think that when we initially talked about the v1 of the landing page, we would eventually have an interactive demo within the page that people would not have to click out to a new page. If that were the case, then perhaps the previous version would work better.

**Comment by prakhargupta1** [comment] 2022-10-27 03:53
This looks perfect!

**Comment by gerdadesign** [comment] 2022-10-27 15:00
I agree that open source is an important aspect to communicate. We have "open-source" written in the intro and below the features, the upvote button leads to github. Is there something outside of these that you feel is missing? 

I'm hesitant to add a 3rd CTA in the top header as that can feel overwhelming and confusing — ex. I land on this page to learn about this new thing called Toolpad, read a short summary of what this product is, then see that there are multiple immediate links out of the page, so I may not come back to it.

**Comment by bharatkashyap** [comment] 2022-10-27 15:41
> I agree that open source is an important aspect to communicate. We have "open-source" written in the intro and below the features, the upvote button leads to github. Is there something outside of these that you feel is missing? 
> 
> 
> 
> I'm hesitant to add a 3rd CTA in the top header as that can feel overwhelming and confusing — ex. I land on this page to learn about this new thing called Toolpad, read a short summary of what this product is, then see that there are multiple immediate links out of the page, so I may not come back to it. 

Fair enough! Let's go ahead with the version above.

**Comment by prakhargupta1** [comment] 2022-10-27 16:24
> Also, do we update the "Want to try it first?" copy on the self-host section now, given that there is an option to try it without self-hosting?

Good point! Some suggestion: `Liked the demo and want to explore further? Install Toolpad alpha securely. [Self-host]`

**Comment by gerdadesign** [comment] 2022-10-27 19:05
agreed about updating the copy! 

I looked at how retool and appsmith described self-host vs cloud and the mention "infrastructure" A LOT. Perhaps we want to play off the same key word? My (condensed) suggestion: 

#### Try Toolpad on your own infrastructure.
**[Self-host >]**

**Comment by bytasv** [comment] 2022-10-28 06:00
Just a few cents from my own perspective - when I read **infrastructure**, something more complex comes to my mind, I would never call my own laptop "infrastructure" 🤔 I was thinking that something along the lines of "Setup Toolpad on your local machine" maybe would better indicate that it should be fairly easy? 🤔

**Comment by gerdadesign** [comment] 2022-10-28 21:23
Hmm what if we went with a more colloquial header, but kept "infrastructure" as a keyword. I'm honestly not sure if it makes a huge difference in search or ranking, but it's a common keyword (along with "on-premise") I'm seeing across Retool, Appsmith, Budibase, Superblocks, etc  so it may be a good word to include for comparison? Interested if there are any data points around this! 

![Image](https://user-images.githubusercontent.com/106991024/198735099-3300514e-35e5-47ef-8ec9-d931e637f404.png)

I'm also noticing that others go in depth about the benefits and features of self-hosting vs cloud, especially for enterprise customers. Perhaps we should build out the page the CTA brings you to a bit: https://mui.com/toolpad/getting-started/installation/

VS
https://retool.com/self-hosted/
https://docs.appsmith.com/getting-started/setup
https://docs.superblocks.com/on-premise-agent/overview
https://docs.budibase.com/docs/hosting-methods

**Comment by bharatkashyap** [comment] 2022-10-29 12:42
> Hmm what if we went with a more colloquial header, but kept "infrastructure" as a keyword. I'm honestly not sure if it makes a huge difference in search or ranking, but it's a common keyword (along with "on-premise") I'm seeing across Retool, Appsmith, Budibase, Superblocks, etc so it may be a good word to include for comparison? Interested if there are any data points around this! _Would also appreciate if you have any insight, @samuelsycamore !_
> 
> ![Image](https://user-images.githubusercontent.com/106991024/198735099-3300514e-35e5-47ef-8ec9-d931e637f404.png)
> 
> I'm also noticing that others go in depth about the benefits and features of self-hosting vs cloud, especially for enterprise customers. Perhaps we should build out the page the CTA brings you to a bit: https://mui.com/toolpad/getting-started/installation/
> 
> VS https://retool.com/self-hosted/ https://docs.appsmith.com/getting-started/setup https://docs.superblocks.com/on-premise-agent/overview https://docs.budibase.com/docs/hosting-methods

I feel like the subtitle here almost looks like a pitch for the enterprise version of Toolpad whereas the intention for us right now is to convert an individual developer who is intrigued enough by the landing page into a member of the community. 

So I think, something like "Try out the alpha version on your own infrastructure and start contributing to Toolpad" could make more sense for the subtitle

**Comment by prakhargupta1** [comment] 2022-10-31 08:30
Although, Infrastructure is applicable for enterprise companies where they have their own servers on a private network, I think it is an accepted term. Used along with self-host conveys the meaning.

> So I think, something like "Try out the alpha version on your own infrastructure and start contributing to Toolpad" could make more sense for the subtitle.
I don't think it is relevant at this place maybe we can write it somewhere else. Also, currently, 'open-source' isn't being shown properly. We can do this all together.

Copy for subtitle: **Using Docker, you can host Toolpad on your own secure infrastructure.**
I mentioned Docker as it quickly explains how you can install it.

**Comment by gerdadesign** [comment] 2022-11-02 14:54
updated the copy at the bottom in [figma](https://www.figma.com/file/4uv2dT18rXJPZBbrbpw61q/Marketing-site?node-id=5817%3A52821)

**Closed** 2022-12-06 18:48 UTC
Labels: design: ui, website
