### ISSUE TITLE
Canvas just shows infinite spinner when running npm run dev on Windows

### ISSUE THREAD

**Issue by dprothero** [mui/mui-toolpad#2431] opened 2023-08-05 14:45 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Use Windows 11, from PowerShell
2. `npx create-toolpad-app budget-ui`
3. `cd budget-ui`
4. `npm run dev`

### Current behavior 😯

The tool loads at a url like `http://localhost:3000/_toolpad/app/pages/0BLHdTc` but the canvas just shows a circular spinner. I am unable to drop any components onto the canvas (the mouse pointer turns into a 🚫)

![image](https://github.com/mui/mui-toolpad/assets/1897006/801c6c1c-7150-49b5-9f6c-6aa486a5b36c)

When I went to take the above screenshot (Windows key + Shift + S), the browser view changed to the following:

![image](https://github.com/mui/mui-toolpad/assets/1897006/08b23ab8-53c7-4ca8-9039-89cca3c709ea)

### Expected behavior 🤔

The toolpad canvas should load as shown in the tutorial and I should be able to drag components onto it.

### Context 🔦

I'm just trying to run the tutorial.

### Your environment 🌎

Edition	Windows 11 Pro
Version	22H2
OS build	22621.1992
Experience	Windows Feature Experience Pack 1000.22644.1000.0

Running from PowerShell command prompt (non-admin)

Node.js 18.13.0

@mui/toolpad 0.1.22

**Comment by Natalie-Perez** [comment] 2023-08-07 02:15
I was experiencing the same issue. Stopping and re-running the project a few times got it to work. I didn't do anything helpful to fix the issue so I'm unsure why it started working.


My environment 🌎
Edition Windows 10 Pro
Version 22H2
OS build 19045.3208
Experience Windows Feature Experience Pack 1000.19041.1000.0

Running from Git Bash command prompt (non-admin)

Node.js 16.14.2

@mui/toolpad 0.1.22

**Comment by apedroferreira** [comment] 2023-08-07 19:11
I can reproduce similar behavior when running the latest version, this is the error I get:
![Capture](https://github.com/mui/mui-toolpad/assets/10789765/adf68353-13b2-491b-85e3-c634e3e79e7c)
Looking into it to try to figure out the cause, thanks for submitting this issue!

**Comment by apedroferreira** [comment] 2023-08-10 18:42
This should be fixed in the latest version of Toolpad.
Will wait to see if we get any more similar reports over the next couple of weeks.

**Comment by apedroferreira** [comment] 2023-08-23 17:02
It's been 2 weeks and I think we fixed it, so will close this issue.
If anything like this pops up again please feel free to create a new issue!

**Closed by apedroferreira** 2023-08-23 17:02 UTC
Labels: bug 🐛
