### ISSUE TITLE
Support custom link text & url in table column

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#1649] opened 2023-02-12 13:53 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

In https://master--toolpad.mui.com/_toolpad/app/cl4hla83p01949xoizo5uxf2a/pages/f303n5n I have a link column type, it looks like this:

<img width="351" alt="Screenshot 2023-02-12 at 14 52 23" src="https://user-images.githubusercontent.com/3165635/218315131-347c0848-6d67-4f30-954c-fbf47ff99425.png">

<img width="280" alt="Screenshot 2023-02-12 at 14 54 12" src="https://user-images.githubusercontent.com/3165635/218315171-605dc1e6-92af-4e25-8674-bed66589529a.png">

However, I don't care about the actual URL. It would be nice to be able to replace the value with something like "Open". 

### Examples 🌈

It's possible in Metabase:
<img width="374" alt="Screenshot 2023-02-12 at 14 50 48" src="https://user-images.githubusercontent.com/3165635/218315075-82d676f9-b434-4513-a23e-12583dac663a.png">

### Motivation 🔦

Simpler display. Sure, I can create a custom column component, but it feels like too much effort for this problem (which is also why this is `priority: low`).

**Comment by Janpot** [comment] 2023-02-12 13:56
duplicate of https://github.com/mui/mui-toolpad/issues/1561

**Closed by Janpot** 2023-02-12 13:56 UTC
Labels: duplicate, new feature, waiting for 👍, priority: low
