### ISSUE TITLE
Wrong default layout

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#753] opened 2022-08-06 17:38 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The information here are inaccurate

### Expected behavior 🤔

Accurate value

### Steps to reproduce 🕹

[Uploading Screen Recording 2022-08-06 at 19.37.24.mov…](https://user-images.githubusercontent.com/3165635/183259893-43a371fb-b67c-4d88-908b-760f71981837.mov
)

### Context 🔦

It's not important, only reporting it to collect upvotes, to not fix yet.

**Comment by Janpot** [comment] 2022-08-08 08:11
duplicate of https://github.com/mui/mui-toolpad/issues/755

**Closed by Janpot** 2022-08-08 08:11 UTC
Labels: bug 🐛, waiting for 👍
