### ISSUE TITLE
Changing query name reset all the settings 

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#1157] opened 2022-10-13 23:44 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

All my options are lost, transformation, params, etc.

### Expected behavior 🤔

The dialog keeps all the options set.

### Steps to reproduce 🕹

Steps:

1. Open https://master--toolpad.mui.com/_toolpad/app/cl7z6bymv24562awr0skxffqio/pages/ne1a0zn
2. Click Add query
3. Pick a "Fetch | default"
4. Add `https://api.github.com/repos/mui/mui-x/issues` in the get URL.
5. Focus the name field
6. Change the value
7. Blur the field 💥

https://user-images.githubusercontent.com/3165635/195729389-0aeed02e-e5f3-4ea9-9c35-b8e49f389ad9.mov

### Context 🔦

I face this problem while I was building a quick UI for Greg to help us with the support on GitHub https://www.notion.so/mui-org/Set-GitHub-scope-labels-12a84fdf50e44595afc55343dac00fca#3f39c7660fc448b1a6c0f554a29a5ce2. If you are interested about the other pains I faced but I didn't open issues for you will find:

- Duplicate queries https://github.com/mui/mui-toolpad/issues/1172
- Data grid column type link (see Metabase for an example) https://github.com/mui/mui-toolpad/issues/827
- Undo (I pressed the Recrete columns icon button by mistake) https://github.com/mui/mui-toolpad/issues/226
- Support for the size prop with the button to be smaller. 

But I only open an issue for my biggest pain. BTW, I love the new query UI. Building the whole UI felt fast, I'm not sure I would have been quicker the pro-code way;

### Your environment 🌎

v0.0.22

**Comment by Janpot** [comment] 2022-10-14 07:43
I think this has the same root cause as https://github.com/mui/mui-toolpad/issues/1126. Tackling https://github.com/mui/mui-toolpad/issues/1126 should solve this issue as well.

**Comment by Janpot** [comment] 2022-10-19 16:40
it's related. The name change input operates directly on the dom (it uses a shared component that's used throughout Toolpad). The rest of the dialog operates on a draft copy. when the dom changes the draft copy gets updated to the actual value in the dom. That's why changing the name resets the fields.

Solution: the name change input needs to operate on the draft copy as well. The part that's slightly tricky will be about how to deal with duplicate names.

**Comment by apedroferreira** [comment] 2022-10-19 16:47
@Janpot I assigned this to myself because I thought I could take it but let me know if you think you should take it instead, I can find other tasks.

**Comment by Janpot** [comment] 2022-10-20 12:41
I was going to take it but wanted to merge https://github.com/mui/mui-toolpad/pull/1149 first

I'll close this ticket as a duplicate of https://github.com/mui/mui-toolpad/issues/1126

**Closed by Janpot** 2022-10-20 12:41 UTC
Labels: bug 🐛, feature: Queries
